In [1]:
import gym
import numpy as np
import math

In [2]:
env = gym.make('CartPole-v0')

In [3]:
env.reset()
env.render()

True

In [30]:
state = np.random.uniform(-0.05, 0.05, 4)
viewer=None
mode='human'

# Angle at which to fail the episode
theta_threshold_radians = 12 * 2 * math.pi / 360
x_threshold = 2.4

################################################################
screen_width = 600
screen_height = 600

world_width = x_threshold*2
scale = screen_width/world_width
#scale=1
carty = 100 # TOP OF CART
polewidth = 10.0
polelen = scale * (2 * length)
cartwidth = 50.0
cartheight = 30.0
print('Scale:', scale)

if viewer is None:
    from gym.envs.classic_control import rendering
    viewer = rendering.Viewer(screen_width, screen_height)
    l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2
    axleoffset =cartheight/4.0
    print(l, r, t, b)
    cart = rendering.FilledPolygon([(l,b), (l,t), (r,t), (r,b)])
    carttrans = rendering.Transform()
    cart.add_attr(carttrans)
    viewer.add_geom(cart)
    
    l,r,t,b = -polewidth/2,polewidth/2,polelen-polewidth/2,-polewidth/2
    print(l, r, t, b)
    pole = rendering.FilledPolygon([(l,b), (l,t), (r,t), (r,b)])
    pole.set_color(.8,.6,.4)
    poletrans = rendering.Transform(translation=(0, axleoffset))
    pole.add_attr(poletrans)
    pole.add_attr(carttrans)
    viewer.add_geom(pole)
    
    axle = rendering.make_circle(polewidth/2)
    axle.add_attr(poletrans)
    axle.add_attr(carttrans)
    axle.set_color(.5,.5,.8)
    viewer.add_geom(axle)
    
    track = rendering.Line((0,carty), (screen_width,carty))
    track.set_color(0,0,0)
    viewer.add_geom(track)

    _pole_geom = pole
viewer.render(return_rgb_array = mode=='rgb_array')
gg
# Edit the pole polygon vertex
pole = _pole_geom
l,r,t,b = -polewidth/2,polewidth/2,polelen-polewidth/2,-polewidth/2
pole.v = [(l,b), (l,t), (r,t), (r,b)]

x = state
cartx = x[0]*scale+screen_width/2.0 # MIDDLE OF CART
carttrans.set_translation(cartx, carty)
poletrans.set_rotation(-x[2])

viewer.render(return_rgb_array = mode=='rgb_array')

Scale: 125.0
-25.0 25.0 15.0 -15.0
-5.0 5.0 120.0 -5.0


NameError: name 'gg' is not defined

In [4]:
def make_oval(width=10, height=10, res=30, filled=True):
    points = []
    for i in range(res):
        ang = 2*math.pi*i / res
        points.append((math.cos(ang)*width/2, math.sin(ang)*height/2))
    if filled:
        return rendering.FilledPolygon(points)
    else:
        return rendering.PolyLine(points, True)

In [10]:
state = [0]*16
agent_pos = np.random.choice(range(15), 1, replace=False)[0]
state[15] = 1
state[agent_pos] = 3
state = np.array(state).reshape(4, 4)
print(state)
#viewer=None
mode='human'

n_squares_height = 4
n_squares_width = 4

################################################################
screen_width = 600
screen_height = 600

square_size_height = screen_height/n_squares_height
square_size_width = screen_width/n_squares_width

if viewer is None:
    from gym.envs.classic_control import rendering
    viewer = rendering.Viewer(screen_width, screen_height)
    #horizontal grid lines
    for i in range(1, n_squares_height):
        track = rendering.Line((0,i*square_size_height), (screen_width,i*square_size_height))
        track.set_color(0,0,0)
        viewer.add_geom(track)
    #vertical grid lines
    for i in range(1, n_squares_width):
        track = rendering.Line((i*square_size_width, 0), (i*square_size_width, screen_height))
        track.set_color(0,0,0)
        viewer.add_geom(track)
    #the agent
    agent = make_oval(width=square_size_width/2, height=square_size_height/2)
    agenttrans = rendering.Transform()
    agent.add_attr(agenttrans)
    viewer.add_geom(agent)
    #the goal
    goal = make_oval(width=square_size_width/2, height=square_size_height/2)
    goal.set_color(0,255,0)
    goaltrans = rendering.Transform()
    goal.add_attr(goaltrans)
    viewer.add_geom(goal)

goal_pos = list(zip(*np.where(state == 1)))[0]
agent_pos = list(zip(*np.where(state == 3)))[0]

agent_y = (n_squares_height-agent_pos[0]-0.5) * square_size_height
agent_x = (agent_pos[1]+0.5) * square_size_width
agenttrans.set_translation(agent_x, agent_y)

goal_y = (n_squares_height-goal_pos[0]-0.5) * square_size_height
goal_x = (goal_pos[1]+0.5) * square_size_width
goaltrans.set_translation(goal_x, goal_y)

print(agent_pos)
print(goal_pos)

viewer.render(return_rgb_array = mode=='rgb_array')

gg
# Edit the pole polygon vertex
pole = _pole_geom
l,r,t,b = -polewidth/2,polewidth/2,polelen-polewidth/2,-polewidth/2
pole.v = [(l,b), (l,t), (r,t), (r,b)]

x = state
cartx = x[0]*scale+screen_width/2.0 # MIDDLE OF CART
carttrans.set_translation(cartx, carty)
poletrans.set_rotation(-x[2])

viewer.render(return_rgb_array = mode=='rgb_array')

[[0 0 0 0]
 [0 0 0 3]
 [0 0 0 0]
 [0 0 0 1]]
(1, 3)
(3, 3)


NameError: name 'gg' is not defined